"""Orchestral integration for toolbase.

Orchestral is a Python agent *library*, not a config-file MCP client like
Claude Code or Codex. So "connecting" toolbase to orchestral does not mean
editing a config file -- it means handing an orchestral ``Agent`` the
toolbase tools, in-process.

The clean path is to reuse toolbase's own serve ``Orchestrator``. ``tb
serve`` already discovers installed toolkits, spawns one persistent
subprocess per toolkit (each in its own env), and builds a list of
orchestral ``BaseTool`` proxies (``serve/proxy_tool.py``) that forward calls
to those subprocesses. For Claude Code those proxies are wrapped in an MCP
stdio server; for orchestral we hand the same proxy list straight to
``orchestral.Agent``.

Why not point orchestral's own ``MCPClient`` at ``toolbase serve``? Its
stdio transport is ephemeral: it spawns a fresh server subprocess on
``connect()`` *and on every ``call_tool()``*. Against ``toolbase serve``
that would re-spawn the whole orchestrator -- every per-toolkit subprocess
-- on each call. Reusing the ``Orchestrator`` in-process keeps subprocesses
persistent and removes a redundant MCP hop.

Entry points:

- ``toolbase_tools(...)`` -- a context manager yielding the proxy tools as
  orchestral ``BaseTool`` instances, ready for ``Agent(tools=...)``. This is
  the whole integration: toolbase serves the tools; you build and launch the
  agent (orchestral already ships headless / TUI / web-GUI launchers).
- ``agent_script(...)`` -- the runnable scaffold ``tb connect orchestral``
  writes to disk (the library-client analogue of writing ``.mcp.json``).
- ``is_orchestral_available()`` -- detection for ``tb connect --harnesses``.
"""

from __future__ import annotations

import contextlib
import io
from pathlib import Path
from typing import Any, Dict, Iterator, List, Optional, Union

from ..serve.orchestrator import DEFAULT_CALL_TIMEOUT_S, Orchestrator

# The scaffold ``tb connect orchestral`` writes, relative to a project root.
# It lives under ``.toolbase/`` (alongside manifest.yaml / serve.yaml) and is
# launched by ``tb orchestral``.
DEFAULT_SCRIPT_NAME = "orchestral.py"
DEFAULT_SCRIPT_RELPATH = ".toolbase/orchestral.py"

# First line of every generated scaffold. ``tb connect orchestral --remove``
# only deletes a file carrying this marker, so it never removes a script the
# user wrote (or pointed ``--out`` at) by hand.
GENERATED_MARKER = "# Generated by `tb connect orchestral`."


def is_orchestral_available() -> bool:
    """Whether the orchestral library is importable in this environment.

    Orchestral is a hard dependency of toolbase, so this is normally True;
    it only fails in a broken install. ``tb connect --harnesses`` uses it to
    render orchestral's detection status alongside the config-file harnesses.
    """
    import importlib.util

    return importlib.util.find_spec("orchestral") is not None


def _resolve(project_root, profile: Optional[str]):
    """Resolve the active profile, auto-discovering the project root.

    Mirrors ``tb serve``: if ``project_root`` is None we walk up from the
    cwd for a project; absent one, resolution falls through to the user
    layer. ``project_root`` may be a ``str`` or ``Path``; a ``str`` is
    coerced (downstream path handling requires ``Path``).
    """
    from ..envs import find_project_root
    from ..serve.profiles import resolve_profile

    if project_root is None:
        project_root = find_project_root()
    elif not isinstance(project_root, Path):
        project_root = Path(project_root)
    return resolve_profile(project_root, cli_profile=profile)


def _null_console():
    """A Rich console that writes nowhere (suppresses the startup banner)."""
    from rich.console import Console

    return Console(file=io.StringIO())


@contextlib.contextmanager
def toolbase_tools(
    *,
    profile: Optional[str] = None,
    project_root: Optional[Union[str, Path]] = None,
    call_timeout_s: float = DEFAULT_CALL_TIMEOUT_S,
    quiet: bool = False,
    config_overrides: Optional[Dict[str, Any]] = None,
    report: Optional[List[Dict[str, Any]]] = None,
    bare: bool = False,
) -> Iterator[List[Any]]:
    """Spin up toolbase's served tools and yield them as orchestral BaseTools.

    Resolves the active profile (the same chain as ``tb serve``), starts one
    persistent subprocess per served toolkit, and yields the list of proxy
    ``BaseTool`` instances -- ready to pass to ``orchestral.Agent(tools=...)``.
    All subprocesses are torn down when the ``with`` block exits.

    Args:
        profile: profile name to serve (like ``tb serve --profile``). None
            uses the resolution chain (project/user default profile).
        project_root: project to resolve config against. None auto-discovers
            from the cwd, falling back to the user layer.
        call_timeout_s: per-call upper bound passed to the upstream MCP
            clients (default 60s).
        quiet: suppress the orchestrator's startup banner (which otherwise
            prints to stderr).
        config_overrides: state-config keys merged over every served
            toolkit's resolved config before host spawn. The embedding
            harness uses this to scope file-aware tools to its own
            working directory — e.g. a benchmark runner passing
            ``{"base_directory": "<trial sandbox>"}`` so the tools an
            agent calls read/write the same tree the agent's other
            tools see. Keys a toolkit doesn't declare as StateFields
            are ignored by the host.
        report: optional list; when provided, it is extended with one
            ``{toolkit, advertised, served, hidden}`` dict per served toolkit
            so the caller can detect and surface dropped tools even under
            ``quiet=True`` (where the console diagnostics are suppressed).
        bare: advertise tools un-namespaced (``<tool>``) instead of the default
            qualified ``<toolkit>__<tool>``. With multiple toolkits, colliding
            names resolve to the alphabetically-first toolkit's tool.

    Yields:
        A list of orchestral ``BaseTool`` instances (namespaced
        ``<toolkit>__<tool>``).

    Raises:
        NoActiveProfileError / ServeConfigError: no resolvable profile.
        RuntimeError: no toolkit could be started.

    Example::

        from toolbase.connect.orchestral import toolbase_tools
        from orchestral import Agent

        with toolbase_tools(profile="paper") as tools:
            agent = Agent(tools=tools)
            agent.run("analyze run3.csv")
    """
    profile_obj = _resolve(project_root, profile)
    console = _null_console() if quiet else None
    orch_kwargs: dict = dict(
        console=console, profile=profile_obj, call_timeout_s=call_timeout_s,
    )
    if config_overrides:
        # Passed conditionally so test doubles (and any subclass) with the
        # pre-override Orchestrator signature keep working unchanged.
        orch_kwargs["config_overrides"] = config_overrides
    if bare:
        # Conditional for the same back-compat reason (default False == the
        # long-standing namespaced behavior, so old signatures are untouched).
        orch_kwargs["bare"] = bare
    orch = Orchestrator(**orch_kwargs)
    try:
        tools = orch.start()
        if report is not None:
            # Let the caller see how many tools each toolkit dropped (profile /
            # bundle / config gating) — invisible otherwise when quiet=True.
            report.extend(orch.tool_report)
        yield tools
    finally:
        orch.shutdown()


def agent_script(profile: Optional[str] = None) -> str:
    """Return a runnable scaffold that launches an orchestral agent wired with
    toolbase tools. ``tb connect orchestral`` writes this to disk.

    The scaffold builds the agent once and presents all three of orchestral's
    launch modalities -- terminal UI, headless, web GUI -- with the terminal
    UI active and the other two commented out. The user edits to switch.

    Configuring orchestral (the LLM, API keys) is the user's job; the scaffold
    just shows where their LLM plugs in.
    """
    profile_arg = f'profile="{profile}"' if profile else ""
    profile_note = (
        f'serving the "{profile}" profile'
        if profile
        else "serving your active profile"
    )
    return f'''{GENERATED_MARKER} Safe to edit.
#
# Prerequisites (your responsibility -- toolbase does not configure these):
#   * orchestral installed, and your LLM API key in the environment
#     (ANTHROPIC_API_KEY for Claude, OPENAI_API_KEY for GPT, ...).
#
# Run it:   tb orchestral          (or: python {DEFAULT_SCRIPT_RELPATH})
"""Launch an orchestral agent wired with your toolbase tools."""

from toolbase.connect.orchestral import toolbase_tools
from orchestral import Agent
from orchestral.llm import Claude  # swap for GPT, Gemini, ... as you like


def main():
    # `toolbase_tools` spins up one subprocess per served toolkit ({profile_note})
    # and yields the tools as orchestral BaseTool instances. They are torn
    # down when the `with` block exits.
    with toolbase_tools({profile_arg}) as tools:
        agent = Agent(llm=Claude(), tools=tools)

        # -- Pick a launch modality: one is active, the others are commented. --

        # 1) Terminal UI -- interactive chat in your terminal:
        from orchestral.ui import run_interactive_session
        run_interactive_session(agent, streaming=True)

        # 2) Headless -- send one prompt and print the reply:
        # print(agent.run("Summarize the tools you have.").text)

        # 3) Web GUI -- opens a browser (needs orchestral's web extras):
        # from orchestral.ui.app.server import run_server
        # run_server(agent, host="127.0.0.1", port=8000)


if __name__ == "__main__":
    main()
'''


__all__ = [
    "toolbase_tools",
    "agent_script",
    "is_orchestral_available",
    "DEFAULT_SCRIPT_NAME",
    "DEFAULT_SCRIPT_RELPATH",
    "GENERATED_MARKER",
]
